### ISSUE TITLE
Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by Dandu-Venkata-Ravi-Varma** [CSS-Tricks/AnythingZoomer#18]
I use this markup:

```
<div id="zoom">
    <div id="small">
        <img id="image" src="images/1.jpg" alt="example" title="Image" class=" img-polaroid">
    </div>
    <div id="large">
        <img id="image" src="images/1.jpg" alt="example" title="Image" class=" img-polaroid">
    </div>
</div>
```

And I make the call this way:

```
jQuery(document).ready(function(){
    jQuery("#zoom").anythingZoomer()
});
```

My jQuery version is: 1.8.3

It says Cannot read property 'left' of undefined when I hover on an Image,

 https://github.com/CSS-Tricks/AnythingZoomer

Please help.

**Comment by brunonrosa** [comment]
I'm getting this error Cannot read property 'left' of undefined.

I'm trying to apply the plugin on a container of a svg element. Whenever a pass the mouse over the error accurs.

`<div id="container"><svg></svg></div>`
