### ISSUE TITLE
Plugin not showing zoom window when implemented on bootstrap modal

### ISSUE THREAD

**Issue by omkark** [CSS-Tricks/AnythingZoomer#30]
Hi

Following is code for modal

```html
<div class="modal fade" id="viewAlphaArrays" tabindex="-1" role="dialog" aria-labelledby="viewAlphaArray" aria-hidden="true" >
	<div class="modal-dialog" style="width : 76% !important">
		<div class="modal-content">
			<div class="modal-body" style = 'padding: 15px; overflow: scroll;'>
				<div class ='row'  >

					<div id="zoomTiffFirsts">
						<div class="small">
							<img alt="No image available" src = 'http://www.menucool.com/slider/prod/image-slider-5.jpg' class = 'testsmall'>
						</div>

						<div class="large">
							<img alt="No image available" src = 'http://www.menucool.com/slider/prod/image-slider-5.jpg' class = 'testlarge'>
						</div>

					</div>
				</div>

			</div>
			<div class="modal-header" style = 'height : 60px;' >
				<button type="button" class="btn btn-default" data-dismiss="modal" style = 'float : right;margin: 10px;' ng-click = 'resetBrightnessContrast()'>Close</button>
			</div>
		</div>
	</div>
</div>
```

Following is the CSS

```css
.large img.testlarge {
	height : 2118px;
	width : 1050px;
}
.small img.testlatge {
	height : 1412px;
	width : 700px;
}
```

Modal is initially not visible. But when I click a button a function is called from where modal is triggered to open using jquery

Just below that code I inserted code to initialize anythingzoomer

```js
$("#zoomTiffFirsts").anythingZoomer({ switchEvent: '' });
```

But when modal is opened, I am not able to see any image

Please help me with this

Regards

**Comment by omkark** [comment]
HTML Code for above thread

 <div class="modal fade" id="viewAlphaArrays" tabindex="-1" role="dialog" aria-labelledby="viewAlphaArray" aria-hidden="true" >
        <div class="modal-dialog" style="width : 76% !important">
            <div class="modal-content">
                <div class="modal-body" style = 'padding: 15px; overflow: scroll;'>
                    <div class ='row' style = 'text-align : center;-webkit-filter:contrast({{image.contrastForArrayQCImage}}) brightness({{image.brightnessForArrayQCImage / 10}});filter: brightness({{image.brightnessForArrayQCImage / 10}}) contrast({{image.contrastForArrayQCImage}};overflow : hidden' >
                        <div id="zoomTiffFirsts">
                            <div class="small">
                                <img alt="No image available" src = 'http://www.menucool.com/slider/prod/image-slider-5.jpg' class = 'testsmall'>
                            </div>

                            <div class="large">
                                <img alt="No image available" src = 'http://www.menucool.com/slider/prod/image-slider-5.jpg' class = 'testlarge'>
                            </div>

                        </div>     
                    </div>


                </div>
                <div class="modal-header" style = 'height : 60px;' >
                    <button type="button" class="btn btn-default" data-dismiss="modal" style = 'float : right;margin: 10px;' ng-click = 'resetBrightnessContrast()'>Close</button>
                </div>
            </div>
        </div>
    </div>

**Comment by Mottie** [comment]
Hi @omkark!

I think you need to include a refresh of AnythingZoomer once the Bootstrap modal opens. Try this ([demo](http://jsfiddle.net/f6d49/58/)):

```js
$('#viewAlphaArrays').on('shown.bs.modal', function () {
    $("#zoomTiffFirsts").anythingZoomer();
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
