### ISSUE TITLE
Is it possible to rotate zoomer automatically on page load

### ISSUE THREAD

**Issue by amitchoubey** [CSS-Tricks/AnythingZoomer#33]
I am trying to rotate zoomer from left to right automatically on page load, but I am not getting a possible way to rotate & zoom automatically.

**Comment by Mottie** [comment]
Hi @amitchoubey!

Can you please elaborate, what do you mean by rotate zoomer from left to right?

If you would please, modify [this demo](http://jsfiddle.net/Mottie/f6d49/) to show what you have so far and maybe I can help troubleshoot the problem.

**Comment by amitchoubey** [comment]
I want that on page load magnifier box will move on text or image from left position to right position automatically without moving mouse. Its like we are showing demo to some how AnythingZoomer works when we manually move mouse over image or text.

**Comment by Mottie** [comment]
Hi, yes it is possible.

It's not pretty, at least to me... [here is a demo](http://jsfiddle.net/Mottie/f6d49/76/) that allows you to set a start and end position, duration and easing for the animation.

```js
var curLeft = 70,
	curTop = 50,
	endLeft = 150,
	endTop = 70,
	zoomWindowSize = 100,
	duration = 'slow',
	easing = 'linear',
	$zoom = $( '#zoom' ).anythingZoomer();

// ** DON'T CHANGE ANYTHING BELOW **
$zoom.anythingZoomer( curLeft, curTop, [ zoomWindowSize, zoomWindowSize ] );

// add a dummy div to animate; so we get the correct
// left & top position for the zoom window
var $div = $( '<div>', {
	css: {
		position: 'absolute',
		left: curLeft,
		top: curTop
	}
}).appendTo('body');
$div.animate({
	left: '+=' + ( endLeft - curLeft ),
	top: '+=' + ( endTop - curTop )
}, {
	step: function ( now, tween ) {
		if ( tween.prop === 'left' ) {
			curLeft = now;
		} else {
			curTop = now;
		}
		// update AnythingZoomer
		$zoom.anythingZoomer( curLeft, curTop );
	},
	duration: duration,
	easing: easing,
	complete: function(){
		$div.remove();
	}
});
```

**Comment by amitchoubey** [comment]
@Mottie Thanx for demo and help.
