### ISSUE TITLE
Responsive Image

### ISSUE THREAD

**Issue by programaction** [CSS-Tricks/AnythingZoomer#35]
Hi,

Is there a way to make it work with responsive image?

Thank you

JF

**Comment by Mottie** [comment]
What exactly do you mean by responsive image? Would you please modify [this demo](http://jsfiddle.net/Mottie/hno8q31c/) to illustrate what you mean.

If you want to programmatically update the plugin, call anything zoomer without any options:

```js
// update plugin
$('.zoom').anythingZoomer();
```

**Comment by programaction** [comment]
I would like the zoom container or the image width in % so it adjust to the screen size.
Is this possible?

**Comment by Mottie** [comment]
Using a percentage width is not currently possible.

Initially, I was thinking you meant you were using `@media` css definitions to step-wise change the image dimensions. If that was the case, then you would only need to update the plugin after the window `resize` event has stopped firing.

**Comment by programaction** [comment]
I will have to use @media then...

Thank you.
