### ISSUE TITLE
Enable/Disable Anything Zoomer

### ISSUE THREAD

**Issue by sjp700** [CSS-Tricks/AnythingZoomer#37]
I have added a button to enable/ disable AnythingZoomer so I can use d3 pan/drag/zoom on a chart when it is disable or use Anything Zoomer over the chart when it is enabled.  Is there a way to do this?  I've tried   $('#zoom3').data('zoomer').setEnabled(false); but it didn't work.

**Comment by Mottie** [comment]
Hi @sjp700!

Hmm, that method does work for me ([demo](http://jsfiddle.net/Mottie/6sp2b/266/)), so I'm not sure why there's an issue.

Anyway, the "official" method to enable or disable AnythingZoomer is to do the following ([demo](http://jsfiddle.net/Mottie/6sp2b/265/)):

```js
$('#zoom3').anythingZoomer('disable');
```

While making the demo, I noticed that after hovering over the disabled zoomers, the zoom window would reappear when the zoomer is re-enabled. I'll have that problem fixed soon.
